### PR TITLE
Restore the generic bin/rails command

### PR DESCRIPTION
**Pull request by elia**
Fixes https://github.com/solidusio/solidus_dev_support/issues/86.

## Summary

Move the sandbox and engine specializations to their own rails-* files.

By default generate commands will be run in the context of the engine
while any other command will be run from the sandbox. With the
additional bin/rails-* files it will be more easy to find how to run
a command from a specific context.

The old files have been kept with added deprecation notices.

## Checklist

- [x] I have structured the commits for clarity and conciseness.
- [x] I have added relevant automated tests for this change.
- [x] I have added an entry to the changelog for this change.

### CODE REVIEW

**Comment by peterberkenbosch** [comment]
Nice, way better naming that my `r` :). Love it that we can just use `rails g` again on extensions!

**Comment by aldesantis** [comment]
@elia I'm not 100% sure we need the deprecation tbh, considering that `bin/r` is a generated binary and not some kind of public API.

**Comment by elia** [comment]
@peterberkenbosch this is the result of my extreme laziness and desire for comfort while developing 😅

@aldesantis since I already seen executables accumulating inside bin/ as the result of multiple runs of `solidus extension` I think in the next major we should actively propose to remove the deprecated files. I'm also quite sure that developing the ability to delete files (always asking) within the generator will come in handy in the future for other generated files as well (off the top of my mind removing empty assets and similar things).

**Comment by peterberkenbosch** [comment]
> @elia I'm not 100% sure we need the deprecation tbh, considering that `bin/r` is a generated binary and not some kind of public API.

also not 1.0 released yet, the bin/r etc only lived in a release for a bit. I'm okay with removing this.

**Pull request merged**
