### PR TITLE
Switch to main branch

### PR DESCRIPTION
**Pull request by mamhoff**
## Summary

This changes all references to the `master` branch in the repository to `main` in anticipation of changing the default branch on the repo to `main`.

## Checklist

Check out our [PR guidelines](https://github.com/solidusio/.github/blob/master/CONTRIBUTING.md#pull-request-guidelines) for more details.

The following are mandatory for all PRs:

- [x] I have written a thorough PR description.
- [x] I have kept my commits small and atomic.
- [x] [I have used clear, explanatory commit messages](https://github.com/solidusio/.github/blob/main/CONTRIBUTING.md#writing-good-commit-messages).

The following are not always needed:

- 📖 I have updated the README to account for my changes.

### CODE REVIEW

**Comment by kennyadsl** [comment]
Thanks @mamhoff. Does this mean that by merging this PR we will need to change the default branch of all extensions (to keep them aligned with the default template)? I'm a bit scary about the work needed for that. 

On the other side, if you create an extension today using the template, it will create it with the wrong default branch name. 

@solidusio/core-team @solidusio/nebulab any thoughts?

**Comment by mamhoff** [comment]
Most of this affects only new extensions as far as I can oversee: gemspec, README and so on. The only change I'm not so sure about what it does is the `mergify` one, but I don't imagine that the `mergify.yml` in this repo would affect any other repo?

**Comment by kennyadsl** [comment]
When you execute the task again on an existing extension, it will keep asking to update those pieces over and over again. Not a big deal though, as you mentioned, it will only in places that you probably don't want to update anyway.

**Comment by kennyadsl** [comment]
For mergify: I think you are right, it doesn't impact any other repo, but merging this PR we should change the default branch here to have it working.

**Comment by waiting-for-dev** [comment]
I think that renaming `master` to `main` for all the supported extensions (the ones in `solidusio`) is very straightforward: doing the rename and creating very minor (and probably mostly cosmetic because of the automatic redirects). So I'd merge this PR once that's being done. What do you think?

**Comment by waiting-for-dev** [comment]
I renamed the branch accordingly.

**Comment by waiting-for-dev** [comment]
All not-archived extensions on the `solidusio` organization are now using `main` as the default branch name.

**Pull request merged**
